CREATE OR REPLACE TRIGGER DISTANCE_PLACES_UPDATE
    INSTEAD OF UPDATE ON DISTANCE_PLACES
    REFERENCING OLD as o NEW as n
    FOR EACH ROW
    BEGIN
        UPDATE PLACES_IN_UK
        SET LONGITUDE = n.LONGITUDE,
            LATITUDE = n.LATITUDE
        WHERE ID = n.ID;
    END;