CREATE OR REPLACE VIEW AVG_DISTANCE AS (
    SELECT
        PIU1.ID AS ID,
        PIU1.NAME AS NAME,
        ROUND4(AVG(HAVERSINE(PIU1.LONGITUDE,PIU1.LATITUDE,PIU2.LONGITUDE,PIU2.LATITUDE))) AS AVG_DISTANCE
    FROM PLACES_IN_UK PIU1
    CROSS JOIN PLACES_IN_UK PIU2
    WHERE PIU1.ID != PIU2.ID
        AND PIU1.LATITUDE < 55.4
        AND PIU2.LATITUDE < 55.4
    GROUP BY PIU1.ID, PIU1.NAME
);