-- Query result:
-- For all brands and manufacturers , output the items that are in the lowest 1,5%
-- of the brand's price range (closed interval).
-- The price range is the interval between the cheapest and most expensive item.
-- Arrange the results in ascending order by manufacturer and brand, and then in descending order by name.
--
-- Result scheme:
-- [MFGR (↑1) | BRAND (↑2) | NAME (↓3)]
--
-- Points:
-- 0.5
--
