-- Query result:
-- Output all suppliers who carry at least one item (part) from the manufacturer “Manufacturer#2”
-- or the brand “Brand#52”.
-- Arrange the result in descending order by name.
--
-- Result schema:
-- [NAME (↓) | ADDRESS | PHONE]
--
-- Points:
-- 0.25
--
