-- Task 3:
--
-- Points:
-- 0.5
--
ALTER TABLE CustomerContactData
    ADD CONSTRAINT CCD_Customer_FK
    FOREIGN KEY (CUSTKEY)
    REFERENCES CUSTOMER (CUSTKEY)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;

