-- Creating the table

CREATE TABLE PhoneChanges(
    CHANGEDATE TIMESTAMP NOT NULL,
    CUSTKEY INTEGER NOT NULL,
    OLDPHONE VARCHAR(50),
    FOREIGN KEY(CUSTKEY) REFERENCES CUSTOMER(CUSTKEY)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    PRIMARY KEY (CHANGEDATE, CUSTKEY)
);