CREATE OR REPLACE FUNCTION HAVERSINE(LON1 DOUBLE, LAT1 DOUBLE, LON2 DOUBLE, LAT2 DOUBLE)
RETURNS DOUBLE
BEGIN
    DECLARE R INTEGER DEFAULT 6371;

    DECLARE D_LON DOUBLE;
    DECLARE D_LAT DOUBLE;
    DECLARE S_LAT DOUBLE;

    DECLARE a DOUBLE;
    DECLARE d DOUBLE;

    -- Calculate differences first
    SET D_LON = RADIANS(LON2) - RADIANS(LON1);
    SET D_LAT = RADIANS(LAT2) - RADIANS(LAT1);
    SET S_LAT = RADIANS(LAT2) + RADIANS(LAT1);

    -- Haversine formula
    SET a = SIN(D_LAT / 2) * SIN(D_LAT / 2) + (1 - SIN(D_LAT / 2) * SIN(D_LAT/2)- SIN(S_LAT / 2) * SIN(S_LAT / 2))
        * SIN(D_LON / 2) * SIN(D_LON / 2);

    -- Calculate Distance
    SET d = 2 * R * ASIN(SQRT(a));

    RETURN d;
END;