CREATE OR REPLACE FUNCTION HAVERSINE(LON1 DOUBLE, LAT1 DOUBLE, LON2 DOUBLE, LAT2 DOUBLE)
    BEGIN
        DECLARE R INTEGER DEFAULT 6371;
        DECLARE D_LON DOUBLE DEFAULT RADIANS(LON2 - LON1);
        DECLARE D_LAT DOUBLE DEFAULT RADIANS(LAT2 - LAT1);
        DECLARE a DOUBLE;
        DECLARE c DOUBLE;
        DECLARE d DOUBLE;
        SET a = SIN(D_LAT / 2) * SIN(D_LAT / 2) + COS(RADIANS(LAT1))
            * COS(RADIANS(LAT2)) * SIN(D_LON / 2) * SIN(D_LON / 2);
        SET c = 2 * ATAN2(SQRT(a), SQRT(1-a));
        SET d = R * c;
        RETURN d;
    END